const KEY='elhamNowrooziSite_v3';
const defaults={
 lang:'fa', brand:{name:'ELHAM NOWROOZI',sub:'ARCHITECTURE STUDIO'},
 nav:[{fa:'خانه',en:'Home',href:'#home'},{fa:'خدمات من',en:'My Services',href:'#services'},{fa:'درباره من',en:'About Me',href:'#about'},{fa:'تماس با من',en:'Contact Me',href:'#contact'}],
 hero:{eyebrow:'ARCHITECTURE / INTERIOR / BIM / LANDSCAPE',title:'معماری،\nفراتر از فضاها',desc:'طراحی فضاهایی که با نیازها، سبک زندگی\nو رویاهای شما هماهنگ باشند.',button:'مشاهده خدمات من',enEyebrow:'ARCHITECTURE / INTERIOR / BIM / LANDSCAPE',enTitle:'Architecture,\nBeyond Space',enDesc:'Spaces designed around your needs, lifestyle\nand vision.',enButton:'Explore My Services',img:'/images/hero-sketch.png'},
 servicesTitle:{fa:'خدمات من',en:'My Services'}, servicesEyebrow:'MY SERVICES',
 about:{title:'درباره من',enTitle:'About Me',eyebrow:'ABOUT ME',p1:'من الهام نوروزی، معمار و مهندس عمران با بیش از ۱۵ سال تجربه کاری در حوزه طراحی و اجرای پروژه‌های مسکونی، تجاری و اداری هستم.',p2:'با تکیه بر خلاقیت، دانش فنی و توجه به جزئیات، در تلاش هستم فضاهایی کاربردی، زیبا و ماندگار خلق کنم.',enP1:'I am Elham Nowroozi, an architect and civil engineer with more than 15 years of experience in the design and execution of residential, commercial and office projects.',enP2:'Combining creativity, technical knowledge and attention to detail, I create functional, refined and lasting spaces.',img:'/images/about.jpg',signature:'Elham Nowroozi',stats:[['۱۵+','سال تجربه کاری','15+','Years of Experience'],['◈','تخصص در طراحی مدرن و BIM','◈','Modern Design & BIM'],['♧','تعهد به کیفیت و جزئیات','♧','Quality & Detail']]},
 contact:{title:'برای پروژه خود مشاوره یا سفارش دارید؟',desc:'فرم درخواست پروژه را تکمیل کنید تا در سریع‌ترین زمان با شما تماس بگیریم.',button:'ثبت درخواست پروژه',enTitle:'Have a project in mind?',enDesc:'Send your project request and we will get back to you as soon as possible.',enButton:'Request a Project',email:'elham.nowroozi@gmail.com'},
 footer:{location:'Kish, Iran',email:'elham.nowroozi@gmail.com',phone:'+98 917 256 4289',instagram:'Instagram',linkedin:'LinkedIn'},
 services:{
 plan:{title:'طراحی پلان',en:'Plan Design',img:'/images/plan.jpg',desc:'طراحی پلان‌های معماری متناسب با نیاز و سبک زندگی شما',enDesc:'Architectural plans tailored to your needs and lifestyle',subs:['پلان مسکونی','پلان تجاری','پلان اداری','پلان ویلایی'],subEn:['Residential Plan','Commercial Plan','Office Plan','Villa Plan']},
 facade:{title:'طراحی نما',en:'Facade Design',img:'/images/facade.jpg',desc:'طراحی نماهای مدرن و کلاسیک با متریال و جزئیات خاص',enDesc:'Modern and refined facades with carefully selected materials',subs:['نمای مدرن','نمای کلاسیک','نمای مینیمال','جزئیات نما'],subEn:['Modern Facade','Classic Facade','Minimal Facade','Facade Details']},
 interior:{title:'طراحی داخلی',en:'Interior Design',img:'/images/interior.jpg',desc:'طراحی داخلی لوکس و مینیمال متناسب با سبک زندگی شما',enDesc:'Warm, refined and functional interior spaces',subs:['مسکونی','اداری','تجاری','بازطراحی فضا'],subEn:['Residential','Office','Commercial','Space Redesign']},
 bim:{title:'BIM',en:'BIM Modeling',img:'/images/bim.jpg',desc:'مدل‌سازی اطلاعات ساختمان با دقت و مدیریت پروژه',enDesc:'Accurate BIM modeling and project information management',subs:['مدل‌سازی BIM','Revit','هماهنگی مدل','مدیریت اطلاعات پروژه'],subEn:['BIM Modeling','Revit','Model Coordination','Project Information Management']},
 landscape:{title:'طراحی محوطه',en:'Landscape Design',img:'/images/landscape.jpg',desc:'طراحی محوطه، باغ و فضای سبز برای محیطی زیبا و آرامش‌بخش',enDesc:'Landscape, garden and green-space design',subs:['باغ و فضای سبز','محوطه مسکونی','فضای عمومی','طراحی اقلیمی'],subEn:['Garden & Green Space','Residential Landscape','Public Space','Climate Responsive Design']}
 },projects:[]
};
function clone(x){return JSON.parse(JSON.stringify(x))} function getData(){try{return JSON.parse(localStorage.getItem(KEY))||clone(defaults)}catch{return clone(defaults)}} function saveData(d){localStorage.setItem(KEY,JSON.stringify(d))}
let data=getData(); if(!localStorage.getItem(KEY)) saveData(data); let lang=data.lang||'fa';
const $=id=>document.getElementById(id); const t=(fa,en)=>lang==='fa'?fa:en;
function render(){document.documentElement.lang=lang;document.documentElement.dir=lang==='fa'?'rtl':'ltr';$('brandName').textContent=data.brand.name;$('brandSub').textContent=data.brand.sub;$('nav').innerHTML=data.nav.map(n=>`<a href="${n.href}">${t(n.fa,n.en)}</a>`).join('');
$('heroImg').src=data.hero.img;$('heroEyebrow').textContent=t(data.hero.eyebrow,data.hero.enEyebrow);$('heroTitle').innerHTML=t(data.hero.title,data.hero.enTitle).replace(/\n/g,'<br>');$('heroDesc').innerHTML=t(data.hero.desc,data.hero.enDesc).replace(/\n/g,'<br>');$('heroBtn').innerHTML=t(data.hero.button,data.hero.enButton)+' <span>←</span>';$('servicesEyebrow').textContent=data.servicesEyebrow;$('servicesTitle').textContent=t(data.servicesTitle.fa,data.servicesTitle.en);
$('cards').innerHTML=Object.entries(data.services).map(([k,s])=>`<button class="card" data-service="${k}"><img src="${s.img}"><span class="icon">${k==='bim'?'◇':k==='landscape'?'♧':k==='interior'?'▱':k==='facade'?'▥':'⌗'}</span><strong>${t(s.title,s.en)}</strong><small>${t(s.desc,s.enDesc)}</small><em>→</em></button>`).join('');
$('aboutImg').src=data.about.img;$('aboutEyebrow').textContent=data.about.eyebrow;$('aboutTitle').textContent=t(data.about.title,data.about.enTitle);$('aboutBody').innerHTML=`<p>${t(data.about.p1,data.about.enP1)}</p><p>${t(data.about.p2,data.about.enP2)}</p>`;$('stats').innerHTML=data.about.stats.map(x=>`<div><b>${t(x[0],x[2])}</b><span>${t(x[1],x[3])}</span></div>`).join('');$('signature').textContent=data.about.signature;
$('contactTitle').textContent=t(data.contact.title,data.contact.enTitle);$('contactDesc').textContent=t(data.contact.desc,data.contact.enDesc);$('contactBtn').textContent=t(data.contact.button,data.contact.enButton);$('contactBtn').href='mailto:'+data.contact.email;
$('footer').innerHTML=`<div class="footerBrand"><span class="enmark">EN</span><span><b>${data.brand.name}</b><small>${data.brand.sub}</small></span></div><div>📍 ${data.footer.location}</div><div>✉ ${data.footer.email}</div><div>☎ ${data.footer.phone}</div><div>◎ ${data.footer.instagram} &nbsp; in ${data.footer.linkedin}</div><small>© 2026 Elham Nowroozi. All rights reserved. &nbsp; | &nbsp; <a href="/admin.html">${t('مدیریت سایت','Site Admin')}</a></small>`;
$('lang').textContent=lang==='fa'?'EN':'FA';document.querySelectorAll('.card').forEach(c=>c.onclick=()=>openService(c.dataset.service));document.querySelectorAll('.card').forEach(c=>c.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' ')openService(c.dataset.service)}));}
function openService(key,sub=null){data=getData();lang=data.lang||lang;document.documentElement.lang=lang;document.documentElement.dir=lang==='fa'?'rtl':'ltr';const s=data.services[key];const all=(data.projects||[]).filter(p=>String(p.service)===String(key));const filtered=sub?all.filter(p=>p.sub===sub):all;const title=t(s.title,s.en); const subIndex=sub?((s.subs||[]).findIndex(x=>String(x)===String(sub))):-1; const subImage=subIndex>=0?(s.subImages?.[subIndex]||''):''; const detailImage=subImage||s.img; $('modalContent').innerHTML=`<div class="detail"><div class="detailTop"><div><div class="eyebrow">${s.en.toUpperCase()} / PORTFOLIO</div><h2>${sub?t(sub,s.subEn?.[subIndex]||sub):title}</h2><p>${sub?t('نمونه‌کارهای این زیرمجموعه را در زیر مشاهده کنید.','Explore selected work in this subcategory below.'):t('نمونه‌کارهای تخصصی این خدمت را در زیر مشاهده کنید.','Explore selected work for this service below.')}</p></div><img src="${detailImage}" alt=""></div><div class="subcats"><button class="subcat ${!sub?'selected':''}" data-sub="">${t('همه نمونه‌کارها','All Projects')}</button>${s.subs.map((x,i)=>`<button class="subcat ${sub===x?'selected':''}" data-sub="${x}">${t(x,s.subEn?.[i]||x)}</button>`).join('')}</div><div class="projectGrid">${filtered.length?filtered.map(p=>`<article class="projectCard"><img src="${p.img}" alt=""><div><small>${p.sub||title}</small><h3>${t(p.title,p.enTitle||p.title)}</h3><p>${t(p.desc||'',p.enDesc||'')}</p>${p.file?`<a class="fileLink" href="${p.file}" target="_blank">${t('مشاهده فایل','View File')} ↗</a>`:''}</div></article>`).join(''):`<div class="emptyProjects">${t('هنوز نمونه‌کاری در این زیرمجموعه ثبت نشده است.','No project has been added to this subcategory yet.')}</div>`}</div><a class="goldBtn" href="#contact" onclick="closeModal()">${t('مشاوره و سفارش پروژه','Request a Project')}</a></div>`;$('modal').classList.add('open');document.body.classList.add('modalOpen');$('modalContent').querySelectorAll('.subcat').forEach(b=>b.onclick=()=>openService(key,b.dataset.sub||null));}
function closeModal(){$('modal').classList.remove('open');document.body.classList.remove('modalOpen')} window.closeModal=closeModal;$('lang').onclick=()=>{lang=lang==='fa'?'en':'fa';data.lang=lang;saveData(data);render()};$('theme').onclick=()=>document.body.classList.toggle('light');$('modal').onclick=e=>{if(e.target===$('modal'))closeModal()};render();
window.addEventListener('storage',()=>{data=getData();lang=data.lang||'fa';render()});
document.addEventListener('visibilitychange',()=>{if(!document.hidden){data=getData();lang=data.lang||'fa';render()}});
